# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

project_path = "../.."

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore")

    # Return the number of commits in current git branch
    build_number = number_of_commits()

    Dir.chdir "#{project_path}" do
      sh("flutter packages get")
      sh("flutter clean")
      sh("flutter build ios --release --no-codesign --build-number=#{build_number} -t lib/main_beta.dart")
    end

    build_ios_app(
      workspace: "#{project_path}/ios/Runner.xcworkspace", 
      scheme: "Runner",
      output_directory: "#{project_path}/build/ios",
      output_name: "Runner-#{build_number}.ipa",
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      ipa: "#{project_path}/build/ios/Runner-#{build_number}.ipa",
      changelog: changelog_from_git_commits,
    )
  end
end

